# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MergePolygon
                                 A QGIS plugin
 Plugin for merging two polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-18
        copyright            : (C) 2023 by Priyanshi Pal
        email                : priyaksum2000@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MergePolygon class from file MergePolygon.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MergePolygon import MergePolygon
    return MergePolygon(iface)
