# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ulpin_to_latlong
                                 A QGIS plugin
 plugin to generate latitude and longitude from unique id
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-04-22
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Priyanshi Pal
        email                : priyakusum2000@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ulpin_to_latlong_dialog import ulpin_to_latlongDialog
import os.path


class ulpin_to_latlong:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ulpin_to_latlong_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&ulpin_to_latlong')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ulpin_to_latlong', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = f'{self.plugin_dir}/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ulpin_to_latlong'),
                action)
            self.iface.removeToolBarIcon(action)

    def Upload_Point_Layer1(self):
        id=self.dlg.lineEdit.text()
        r=latlong(id)
        print(r)
        self.dlg.lineEdit_2.setText(r[0])
        self.dlg.lineEdit_3.setText(r[1])

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ulpin_to_latlongDialog()
            self.dlg.pushButton.clicked.connect(self.Upload_Point_Layer1)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

def val(c):
    if c >= '0' and c <= '9':
        return ord(c) - ord('0')
    else:
        return ord(c) - ord('A') + 10
def toDeci(str,base):
    llen = len(str)
    power = 1
    num = 0   
    for i in range(llen - 1, -1, -1):
        if val(str[i]) >= base:
            print('Invalid Number')
            return -1
        num += val(str[i]) * power
        power = power * base
    return num
def latlong(u):
  uniquecode=u.split("-")
  lat=uniquecode[0][:2]
  lat1=lat.replace("Y", "I")
  lat1=lat.replace("Z", "O")
  lat1=toDeci(lat,14)
  lat1-=90
  lat1=str(lat1)
  
  lat2=uniquecode[0][2:4]
  lat2=lat2.replace("Y", "I")
  lat2=lat2.replace("Z", "O")
  lat2=str(toDeci(lat2,32))
  lat2=lat2.rjust(3,"0")
  
  lat3=uniquecode[0][4:6]
  lat3=lat3.replace("Y", "I")
  lat3=lat3.replace("Z", "O")
  lat3=str(toDeci(lat3,32))
  lat3=lat3.ljust(3,"0")
  
  long1=uniquecode[1][:2]
  long1=long1.replace("Y", "I")
  long1=long1.replace("Z", "O")
  long1=toDeci(long1,19)
  long1-=180
  long1=str(long1)

  long1=long1.rjust(2,"0")
  long2=uniquecode[1][2:4]
  long2=long2.replace("Y", "I")
  long2=long2.replace("Z", "O")
  long2=str(toDeci(long2,32))
  long2=long2.rjust(3,"0")

  long3=uniquecode[1][4:6]
  long3=long3.replace("Y", "I")
  long3=long3.replace("Z", "O")
  long3=str(int(long3,32))
  long3=long3.rjust(3,"0")
  
  latitude=lat1+"."+lat2+lat3
  longitude=long1+"."+long2+long3
  r=[]
  r.append(latitude)
  r.append(longitude)
  return r